name: Push-to-EC2
on: [push]
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: "sudo chown -R ubuntu:ubuntu /var/www/hotel-miranda-php/"
          SCRIPT_AFTER: | 
            sudo chown -R www-data:www-data /var/www/hotel-miranda-php/
            sudo systemctl restart apache2
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: "ec2-13-38-94-41.eu-west-3.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/hotel-miranda-php/"

